/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Solver */

#ifndef _Included_Solver
#define _Included_Solver
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Solver
 * Method:    newDriver
 * Signature: (DDDD)J
 */
JNIEXPORT jlong JNICALL Java_Solver_newDriver
  (JNIEnv *, jclass, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     Solver
 * Method:    freeDriver
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_Solver_freeDriver
  (JNIEnv *, jclass, jlong);

/*
 * Class:     Solver
 * Method:    getValues
 * Signature: (JDDD)J
 */
JNIEXPORT jlong JNICALL Java_Solver_getValues
  (JNIEnv *, jclass, jlong, jdouble, jdouble, jdouble);

/*
 * Class:     Solver
 * Method:    freeValues
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_Solver_freeValues
  (JNIEnv *, jclass, jlong);

/*
 * Class:     Solver
 * Method:    getX
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_Solver_getX
  (JNIEnv *, jclass, jlong);

/*
 * Class:     Solver
 * Method:    getY
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_Solver_getY
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
